---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/patients":
    post:
      summary: Create a patient
      tags:
      - Patients
      parameters: []
      responses:
        '201':
          description: patient created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  api_key:
                    type: string
                required:
                - id
                - name
                - api_key
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                patient:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                  - name
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
